{% set name = "django-celery" %}
{% set version = "3.3.1" %}
{% set build = 0 %}
{% set sha256 = "777220f032f0e12072bf457d5350b1318f5b8774e9cc6cc0ee645feb72d194bb" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/celery/django-celery/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
    - celery >=3.1.15,<4.0
  run:
    - python
    - celery >=3.1.15,<4.0

test:
  imports:
    - djcelery
    - djcelery.backends
    - djcelery.contrib
    - djcelery.management
    - djcelery.management.commands
    - djcelery.migrations
    - djcelery.monproj
    - djcelery.tests
    - djcelery.tests.test_backends
  requires:
    - django >=1.8,<2.0

about:
  home: http://celeryproject.org
  license: BSD 2-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Old django celery integration project.

extra:
  recipe-maintainers:
    - kwilcox
