# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "XYwYax2IYPHP2LqGsbFRxvOGx82DBIXmL5l6g4KMj5jsoE2mXZyFVhUhxi47WrNnYoH68bFjv3i2GLZsIspv5Y6dtfOzQ/MD8dWWyqaF0o/h+b1D8rt/KsrUph1xVy6ZLdssylEBZCLo90aiGc48YyFuq5Fpov+e3NDqFssPHDjVb6Npfuxcp3npnxu1eU24KhkF93jqeqQZp3ZfDSRl4QusDa7bGpEtaNFnuZmth1XKJDEw9ht7WzaIetiJp4RFTNHty6066DM3me1es5xegLO4cGiQmEiYjJtDOkhHd6nR/25ZwT62jTlipzeW4iRGL4weBQqak7hzw8LxMiOdFSILsIHisdAAL+b5oo5BK0PEVQWWyT2q4YNQ5XBFwBJ0O+2Cfv+Q+tFCyQKAU6QPewKhKE7BFQetd7TjLukLQerQHwDEOXwCuSOEY6jF+XXBax42uhOO9jJL5L19Rwjw01vYiFpLvyRne9ITxxe9nxPUxHk8rn0xAXFbY3pYRswfcVT08BpabdVtMUAhL1BGpwr0cb1HvWuGzksieCtj/6REl0uzzeaiVa9k+hERa4CAmd/RDTudq+zaGiZvQHgBH5iGAp53t32aKoGZE4EcSC/Fs+LVaHf2CT08AdTmOQtND/XR1MVambB3FoJ4J3kKa4JIRvL0k0nj0FlpWxTDXtM="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
