travis:
  secure:
    BINSTAR_TOKEN: bmSF5BdIXu6eaGXKgV+kZXU8RjwSioi6ZXRUBZROHe/x4NGeGNqtnBGCxMeig+mCpLFAMvEZgBq1vrWrRDR4k60GUn2hLuIQ+V+PjKPSkGdE2tPaQRy1cvz3GAJqkDAE953os9MWEhOBq3Y9/wEJ7ncpYnaA/bEcbXyXulyueXYyz54Yyb/5mUu7Y9XZcqKh61CvwskOZwQ0FesBnQUPT+Vh2Z8qPnvQZKGjyXDnTEcyFsCZ1LwYU37mIPjlg5eJWL49IX22yLQAgQUnln6OKPCXcOV0791an7sq5Vuc0rY6GvhqBexI7Hne2GIfFaqIrdqZtLnpT4PtAcXdBvqkE+bqO8uWPhyUlgP+7n0f3S3FquMtNqsaNPK/wkTnyt4WvjLJQehtjOfJLl5fv7t9xcwRw5zKIJVGKHBezQvCLjbj2sBh7XYk+8UwEzGo4e/kflT+zN1ouwszhncZZweb/8TY3+BN8DsOOIxH2UBD0rr8+XirPnlEvDYI90DeP4jPvtjoKufOEZzMBYEUYZB0mlpf/vsEMwRyXxdiI8RdCUsxrWvzoK+eMuNl7ZU8vaJBFS/1FEcG9leXeVKRHnXkWyXbEbVHv1l6Cp++fqv527kr+kH9MEOrhTIxoZrsRhTZxpQlw6yHVpnssMqqmXilL1VgvOEezna1ZffEdD/vFsM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
