travis:
  secure:
    BINSTAR_TOKEN: Ea8HYy9OxQHb8xfpXvrR6xRt+iQE4zn9PFqFtRG1HhE0Aae++ibRMVhz+btp56qKzRTtLxP6xq8u0ejQqYDTK5vIb5F3pvat6jXFnQWLufAeiT+vwtVJylZJHrefU5BfgdJ9qE2Wsne7FfRoPljFjm0A1sZfYP+JgCP3qpZCPcmKqttvwSn9XafkQQ4L/br9VkF3VNAzAToViqDD4Ib8L3dU6Nv7s4OebNQtxJuHlgeKD3GDf8Vbz/XNafj4LMGihPVBLmccgTqTdQ7lLKImUX/CxaZH1XXqrzt1JSHwQJUxLjPuPDMTgkQecw/O0o537ncQNLRo4Kk0TQzCADZCDwShquzHXCxyCQ0++l6ux0Ym5mxBLGyMB/MAeKO2AVRiqpykv6RDFKHmxEtqfm26oec71HRpJS6yqzz/8KUhDPy+BoHg7JPLOAn3Pr6UKtcbW2y4y+zvYKRHtwfN5bWer5sjChyg8MVb6Jf3K7j/9WEacu1deMPgvBO6kVtaIpj80HnWZ6065IepQ+YwIP0AilC0/ilPseUUAqghWE9xNqKujFVeH3YP1wDDaMvLfhm+N2hvGGd1QJ4OV2nqKPxTdoS+9o5q97IKrrEhB+Dmf2vwBQyqcyhpO6ZmIn+cv+yJGx7+eg6pq9GrMfgc6d+TmdI2fduSkcn5iw2qMOfoE0w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
