travis:
  secure:
    BINSTAR_TOKEN: XYwYax2IYPHP2LqGsbFRxvOGx82DBIXmL5l6g4KMj5jsoE2mXZyFVhUhxi47WrNnYoH68bFjv3i2GLZsIspv5Y6dtfOzQ/MD8dWWyqaF0o/h+b1D8rt/KsrUph1xVy6ZLdssylEBZCLo90aiGc48YyFuq5Fpov+e3NDqFssPHDjVb6Npfuxcp3npnxu1eU24KhkF93jqeqQZp3ZfDSRl4QusDa7bGpEtaNFnuZmth1XKJDEw9ht7WzaIetiJp4RFTNHty6066DM3me1es5xegLO4cGiQmEiYjJtDOkhHd6nR/25ZwT62jTlipzeW4iRGL4weBQqak7hzw8LxMiOdFSILsIHisdAAL+b5oo5BK0PEVQWWyT2q4YNQ5XBFwBJ0O+2Cfv+Q+tFCyQKAU6QPewKhKE7BFQetd7TjLukLQerQHwDEOXwCuSOEY6jF+XXBax42uhOO9jJL5L19Rwjw01vYiFpLvyRne9ITxxe9nxPUxHk8rn0xAXFbY3pYRswfcVT08BpabdVtMUAhL1BGpwr0cb1HvWuGzksieCtj/6REl0uzzeaiVa9k+hERa4CAmd/RDTudq+zaGiZvQHgBH5iGAp53t32aKoGZE4EcSC/Fs+LVaHf2CT08AdTmOQtND/XR1MVambB3FoJ4J3kKa4JIRvL0k0nj0FlpWxTDXtM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
